#pragma once

#define WIFI_SSID "ACADEMICOS"
#define WIFI_PASSWORD ""
#define WIFI_CONNECT_TIMEOUT 10000
#define WIFI_CONNECT_RETRIES 10
#define WIFI_RETRY_INTERVAL 500

#define API_PORT 8080
#define API_ENDPOINT "/api"

#define WIFI_SCAN_INTERVAL 10000
#define WIFI_CACHE_UPDATE_INTERVAL 5000

#define BLE_SCAN_INTERVAL 15000
#define BLE_SCAN_DURATION 10

#define SERIAL_BAUD_RATE 115200

#define WATCHDOG_TIMEOUT_SEC 10

#define MDNS_HOSTNAME "esp32"

#define NVS_NAMESPACE "wifi"
#define NVS_KEY_SSID "ssid"
#define NVS_KEY_PASSWORD "password"
