#pragma once

#define WIFI_SSID "SUA_REDE_AQUI"
#define WIFI_PASSWORD "SUA_SENHA_AQUI"
#define WIFI_CONNECT_TIMEOUT 10000
#define WIFI_CONNECT_RETRIES 10
#define WIFI_RETRY_INTERVAL 500

#define API_PORT 80
#define API_ENDPOINT "/api"

#define WIFI_SCAN_INTERVAL 10000
#define WIFI_CACHE_UPDATE_INTERVAL 5000

#define SERIAL_BAUD_RATE 115200

#define LOG_LEVEL_DEBUG
#define LOG_LEVEL_INFO
#define LOG_LEVEL_WARN
#define LOG_LEVEL_ERROR

#define NVS_NAMESPACE "wifi"
#define NVS_KEY_SSID "ssid"
#define NVS_KEY_PASSWORD "password"
